# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DiscordRPC
                                 A QGIS plugin
 Plugin for have Discord Rich Presence
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-27
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Ryse93
        email                : ryse93yt@outlook.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .discord_rpc_dialog import DiscordRPCDialog
import os.path

from pypresence import Presence

class DiscordRPC:
    def __init__(self, iface):
        self.iface = iface
        self.RPC = None

    def initGui(self):
        # Initialisation de l'instance pypresence.Presence
        self.RPC = Presence('1111927811419164682')
        self.RPC.connect()

        # Définir les détails de votre Rich Presence
        self.RPC.update(
            details="QGIS",
            state="En train de travailler sur une carte",
            large_image="nom-de-votre-icone",
            small_image="nom-de-votre-petite-icone",
            large_text="Description de l'application",
            small_text="Description du statut"
        )

    def unload(self):
        if self.RPC is not None:
            self.RPC.close()